line_length:
- 300 # warning
- 350 # error
identifier_name:
 allowed_symbols: "_"
 min_length: 2
 max_length:
  warning: 90
  error: 1000
 excluded:
  - id
disabled_rules:
- cyclomatic_complexity
- colon
- comma
- control_statement
- function_parameter_count
- trailing_whitespace
- force_cast
- identifier_name
- discarded_notification_center_observer
- function_body_length
excluded:
- Pods
- Weather/Application/AppDelegate.swift
- Weather/Application/SceneDelegate.swift
custom_rules:
    open_iboutlets:
        included: ".*.swift"
        name: "IBOutlet opening"
        regex: '@IBOutlet ?(weak){0,1} var'
        message: "IBOutlet should be private"
        severity: error
    
    open_ibaction:
        included: ".*.swift"
        name: "IBAction opening"
        regex: '@IBAction func'
        message: "IBAction should be private"
        severity: error 
